### PR TITLE
Prepare release 0.1.5

### PR DESCRIPTION
**Pull request by patrick91**
Just a bump in the version. Also runs tests on the upcoming python 3.9

### CODE REVIEW

**Comment by dorianamouroux** [comment]
Any updates on when this could be merged @patrick91 ?

**Comment by patrick91** [comment]
@dorianamouroux I can merge this now, but I don't have permission to publish it on pypi sadly

**Comment by dorianamouroux** [comment]
@patrick91 Thanks for merging it! Is there anyone from your organization with the authority to publish it?

**Comment by patrick91** [comment]
@dorianamouroux unfortunately not, I'll see if I can reach out to the previous maintainer though 😊

**Comment by SmileyChris** [comment]
'lil bump for @patrick91 - any luck contacting the maintainers? I see @mjtamlyn is active on github still, so he seems the most likely person to hunt :)

**Comment by patrick91** [comment]
@SmileyChris I've sent an email to him already 😊 Don't feel at ease sending another email, especially after the ping on GitHub now 😊

Let's wait a bit more, maybe I'll ask a mutual friend for a more friendly ping :)

**Comment by SmileyChris** [comment]
Yeah I was subtly renotifying him with the ping, no need to pester  😆

**Pull request merged**
