### PR TITLE
Support unicode cursor values

### PR DESCRIPTION
**Pull request by Drarok**
Use utf-8 encoding, not ascii, for cursor values

### CODE REVIEW

**Comment by yeahframeoff** [comment]
Looks like this fixes what I tried to accomplish in #20, but in much simpler way.

Good job!

**Comment by yeahframeoff** [comment]
@Drarok are you going to merge/release it?

**Comment by Drarok** [comment]
Oops, sorry. Yes!

**Comment by Drarok** [comment]
@yeahframeoff: A [new version] has been released, hope it works for you!

[new version]: https://pypi.org/project/django-cursor-pagination/0.1.4/

**Pull request merged**
